spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: josephsx24@gmail.com
    password: frja dkmy hnyf fpbq
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    test-connection: false